apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: devops-challenge
spec:
  selector:
    app: node-app
  ports:
    - port: 80 # Puerto expuesto por el servicio
      targetPort: 3000 # Puerto interno del contenedor
